apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service-db
  name: user-service-db-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: user-service-db
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
  labels:
    app: user-service-db
spec:
  selector:
    matchLabels:
      app: user-service-db
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service-db
      name: user-service-db-service


    spec:
      containers:
        - image: mongo:latest
          name: user-service-db

          ports:
            - containerPort: 27017
              name: user-service-db