apiVersion: v1
kind: Service
metadata:
  name: user-service-h2-service
spec:
  type: LoadBalancer
  selector:
    app: user-service-h2
  ports:
    - port: 9003
      name: http
      targetPort: 9003
